spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE

  username: sa
  password: sa
spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: oscharko
    password: demo
    firstName: o
    lastName: scharko
  filter:
    create: All Tasks
server.port: 8080
